import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <StoreProvider>
      {/* <ThemeProvider defaultTheme='dark' storageKey='vite-ui-theme'> */}
      <html lang="en" className="dark">
        <body className={inter.className}>
          {/* <main className="flex flex-col w-screen h-screen"> */}
          {/* <div className="m-2"> */}
          {/* <MainNavigationMenu /> */}
          {/* </div> */}
          {children}
          {/* </main> */}
        </body>
      </html>
      {/* </ThemeProvider> */}
    </StoreProvider>
  );
}
